# Generated by Django 5.0.2 on 2024-02-20 08:19

import django.core.validators
import django.db.models.deletion
import utils.validates.validates
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Local",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Restaurant", "Restaurant"),
                            ("Bar", "Bar"),
                            ("Café", "Café"),
                            ("Ice cream shop", "Ice cream shop"),
                            ("Pizza shop", "Pizza shop"),
                        ],
                        default="Restaurant",
                        max_length=15,
                        verbose_name="Tipo de local",
                    ),
                ),
                (
                    "local_name",
                    models.CharField(
                        max_length=255,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_numbers_and_spaces,
                        ],
                        verbose_name="Nombre del local",
                    ),
                ),
                ("active", models.BooleanField(default=True, verbose_name="Activo")),
                ("address", models.TextField(default="AAA", verbose_name="Direccion")),
                (
                    "image",
                    models.ImageField(
                        null=True, upload_to="locals", verbose_name="Imagen"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Local",
                "verbose_name_plural": "Locales",
            },
        ),
        migrations.CreateModel(
            name="Gallery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="local_gallery_image/",
                        verbose_name="Imagen del local",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locals.local",
                        verbose_name="Gallery",
                    ),
                ),
            ],
            options={
                "verbose_name": "Galeria de imagenes",
                "verbose_name_plural": "Galeria de imagenes",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "category_name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre de la categoria"
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="locals.local",
                        verbose_name="Local",
                    ),
                ),
            ],
            options={
                "verbose_name": "Categoria",
                "verbose_name_plural": "Categorias",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "product_name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del producto"
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo"
                    ),
                ),
                ("active", models.BooleanField(default=True)),
                (
                    "discount",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Descuento de %"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="product_image/",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "stars",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Number of stars between 1 and 5",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Estrellas",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="productCategory",
                        to="locals.category",
                        verbose_name="Category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Producto",
                "verbose_name_plural": "Productos",
            },
        ),
        migrations.CreateModel(
            name="Ingredient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ingredient_name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del ingrediente"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ingredientProduct",
                        to="locals.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ingrediente",
                "verbose_name_plural": "Ingredientes",
            },
        ),
        migrations.CreateModel(
            name="Aggregate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "agregate_name",
                    models.CharField(
                        max_length=255, verbose_name="Nombre del agregado"
                    ),
                ),
                (
                    "measurement_unit",
                    models.CharField(max_length=50, verbose_name="Unidad de medida"),
                ),
                (
                    "measurement_unit_quantity",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        verbose_name="cantidad en unidades de medida",
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Costo"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agregateProduct",
                        to="locals.product",
                        verbose_name="Product",
                    ),
                ),
            ],
            options={
                "verbose_name": "Agregado",
                "verbose_name_plural": "Agregados",
            },
        ),
    ]
