# Generated by Django 5.0.2 on 2024-02-20 11:47

import django.core.validators
import django.db.models.deletion
import utils.validates.validates
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("locals", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Offer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "offer_description",
                    models.TextField(
                        default="AAA", max_length=100, verbose_name="Descripcion"
                    ),
                ),
                (
                    "offer_name",
                    models.CharField(max_length=30, verbose_name="Nombre de la oferta"),
                ),
                ("min_date", models.DateField(verbose_name="Fecha inicial")),
                ("max_date", models.DateField(verbose_name="Fecha final")),
                (
                    "image_first",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="offer_image/",
                        verbose_name="Imagen izquierda",
                    ),
                ),
                (
                    "image_two",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="offer_image/",
                        verbose_name="Imagen centro",
                    ),
                ),
                (
                    "image_three",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="offer_image/",
                        verbose_name="Imagen derecha",
                    ),
                ),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="locals.local"
                    ),
                ),
            ],
            options={
                "verbose_name": "Oferta",
                "verbose_name_plural": "Ofertas",
            },
        ),
        migrations.CreateModel(
            name="Promo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "promo_description",
                    models.TextField(
                        default="AAA", max_length=150, verbose_name="Descripcion"
                    ),
                ),
                (
                    "promo_name",
                    models.CharField(max_length=30, verbose_name="Nombre de la promo"),
                ),
                ("min_date", models.DateField(verbose_name="Fecha inicial")),
                ("max_date", models.DateField(verbose_name="Fecha final")),
                (
                    "local",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="locals.local"
                    ),
                ),
            ],
            options={
                "verbose_name": "Promo",
                "verbose_name_plural": "Promos",
            },
        ),
        migrations.CreateModel(
            name="Winer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "winer_name",
                    models.CharField(
                        max_length=50,
                        validators=[
                            django.core.validators.MinLengthValidator(3),
                            utils.validates.validates.validate_letters_and_spaces,
                        ],
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "winer_ci",
                    models.CharField(
                        max_length=11,
                        validators=[
                            django.core.validators.MinLengthValidator(11),
                            utils.validates.validates.validate_digits,
                        ],
                        verbose_name="Carnet",
                    ),
                ),
                (
                    "winer_movil",
                    models.CharField(
                        max_length=8,
                        validators=[
                            django.core.validators.MinLengthValidator(8),
                            utils.validates.validates.validate_digits,
                        ],
                        verbose_name="Movil",
                    ),
                ),
                (
                    "promo",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="offer.promo",
                        verbose_name="Promo",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ganador",
                "verbose_name_plural": "Ganadores",
            },
        ),
    ]
